### ISSUE TITLE
a37208a (master) panics in release mode

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-bitcoin-spv#13]
```
[user@host:~/projects/rust-bitcoin-spv]$ RUST_BACKTRACE=1 ./target/release/bitcoin_spv --deb test-mainnet.db
2018-11-12 16:32:54 INFO  [bitcoin_spv::database] working with memory database
2018-11-12 16:32:54 INFO  [bitcoin_spv::node] loading headers from database...
2018-11-12 16:32:54 INFO  [bitcoin_spv::node] reading headers and filters ...
2018-11-12 16:32:54 INFO  [bitcoin_spv::node] read 0 headers from the database
2018-11-12 16:32:54 INFO  [bitcoin_spv::dns] reaching out for DNS seed...
2018-11-12 16:32:54 INFO  [bitcoin_spv::dns] received 184 DNS seeds
2018-11-12 16:32:54 INFO  [bitcoin_spv::p2p] trying outgoing connect to 18.195.115.61:8333 peer=0
2018-11-12 16:32:55 INFO  [bitcoin_spv::p2p] client /Bitcoin ABC:0.16.1(EB8.0)/ height: 530361 peer=0
2018-11-12 16:32:55 INFO  [bitcoin_spv::p2p] handshake peer=0
2018-11-12 16:32:56 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000dfd5d65c9d8561b4b8f60a63018fe3933ecb131fb37f905f87da951a from peer=0
2018-11-12 16:32:56 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000922e2aa9e84a474350a3555f49f06061fd49df50a9352f156692a842 from peer=0
2018-11-12 16:32:57 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000dbbb79792303bdd1c6c4d7ab9c21bba0667213c2eca955e11230c5a5 from peer=0
2018-11-12 16:32:57 INFO  [bitcoin_spv::node] received 2000 headers new tip=0000000094fbacdffec05aea9847000522a258c269ae37a74a818afb96fc27d9 from peer=0
2018-11-12 16:32:57 INFO  [bitcoin_spv::node] received 2000 headers new tip=0000000099c744455f58e6c6e98b671e1bf7f37346bfd4cf5d0274ad8ee660cb from peer=0
2018-11-12 16:32:57 INFO  [bitcoin_spv::node] received 2000 headers new tip=0000000011d1d9f1af3e1d038cebba251f933102dbe181d46a7966191b3299ee from peer=0
2018-11-12 16:32:58 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000002d9050318ec8112057423e30b9570b39998aacd00ca648216525fce3 from peer=0
2018-11-12 16:32:58 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000679a1ab3af6da03f13a0bc96d7215e65458b2d2edfa030b5b431e8b3 from peer=0
2018-11-12 16:32:58 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000f914f0d0692e56bd06565ac4de668251b6a29fe0535d1e0031cfd0de from peer=0
2018-11-12 16:32:59 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000770ebe897270ca5f6d539d8afb4ea4f4e757761a34ca82e17207d886 from peer=0
2018-11-12 16:32:59 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000004625a14242beccb38c63a1f770a76ee5788764e6c0abd4129bbc1b9d from peer=0
2018-11-12 16:32:59 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000f04fccc81f37002707e9501a3f7bdcf25f65531f386a2da8af20122e from peer=0
2018-11-12 16:32:59 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000006d6c151db6d4d67356d590a897a11cd7d8111ee989de6f2f548410bf from peer=0
2018-11-12 16:33:00 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000172c5ed49d7dfc29bf9a18a53fa2d050fa37aa210d6d4080fd0c7e67 from peer=0
2018-11-12 16:33:00 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000de1250dc2df5cf4d877e055f338d6ed1ab504d5b71c097cdccd00e13 from peer=0
2018-11-12 16:33:00 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000049172ba3ec1b673cf13e3d0049c1c07bb103ed3fa300e3833480055 from peer=0
2018-11-12 16:33:01 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000495968d19210d3be15bd24fdc19805a0ef15026b0bb4482b04a9da3c from peer=0
2018-11-12 16:33:01 INFO  [bitcoin_spv::node] received 2000 headers new tip=0000000080c3deea35dc3df90a5fbe5f27db52f5e01018ae7d62f8b454c71335 from peer=0
2018-11-12 16:33:01 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000002dfebce284d1e08b6cf04452530891579b7377669865889498de8f3f from peer=0
2018-11-12 16:33:01 INFO  [bitcoin_spv::node] received 2000 headers new tip=00000000504d5fa0ad2cb90af16052a4eb2aea70fa1cba653b90a4583c5193e4 from peer=0
2018-11-12 16:33:02 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000000f80c09687893406279f62da437a6a0b95b8dc096b30c10ce088fc64 from peer=0
2018-11-12 16:33:02 INFO  [bitcoin_spv::node] received 2000 headers new tip=000000000122898b31073a770a97cf599c00672fc8d6ae15652235862f8b76d8 from peer=0
thread '<unnamed>' panicked at 'slice index starts at 6 but ends at 0', libcore/slice/mod.rs:2340:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::slice::slice_index_order_fail
             at libcore/slice/mod.rs:2340
   9: hammersbald::memtable::MemTable::get
  10: hammersbald::bitcoin_support::BitcoinAdapter::fetch_header
  11: bitcoin_spv::database::DBTX::insert_header
  12: bitcoin_spv::node::Node::process
  13: bitcoin_spv::p2p::P2P::event_processor
  14: bitcoin_spv::p2p::P2P::run
  15: <futures_util::future::poll_fn::PollFn<F> as futures_core::future::Future>::poll
  16: futures_executor::thread_pool::PoolState::work
```

**Comment by tamasblummer** [comment]
No plan for RPC. Instead it implements traits defined by rust-lightning. In contrast to c-lightning the goal is to have a single process level 1 (SPV) and 2 (Lightning) stack.
